-- Create all tables for the database
CREATE TABLE api_keys
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    project_id     BIGINT                                    NOT NULL,
    environment_id BIGINT,
    name           VARCHAR(255)                              NOT NULL,
    key_value      VARCHAR(255)                              NOT NULL,
    key_type       VARCHAR(50)                               NOT NULL,
    is_active      BOOLEAN                     DEFAULT TRUE  NOT NULL,
    last_used_at   TIMESTAMP WITHOUT TIME ZONE,
    created_at     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    expires_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT api_keys_pkey PRIMARY KEY (id)
);

CREATE TABLE environments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    project_id  BIGINT                                    NOT NULL,
    name        VARCHAR(255)                              NOT NULL,
    key         VARCHAR(100)                              NOT NULL,
    description TEXT,
    sort_order  INTEGER                     DEFAULT 0     NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    is_active   BOOLEAN                     DEFAULT TRUE  NOT NULL,
    CONSTRAINT environments_pkey PRIMARY KEY (id)
);

CREATE TABLE feature_flags
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY       NOT NULL,
    project_id    BIGINT                                        NOT NULL,
    name          VARCHAR(255)                                  NOT NULL,
    key           VARCHAR(100)                                  NOT NULL,
    description   TEXT,
    flag_type     VARCHAR(50)                 DEFAULT 'BOOLEAN' NOT NULL,
    default_value TEXT,
    is_permanent  BOOLEAN                     DEFAULT FALSE     NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()     NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()     NOT NULL,
    created_by    VARCHAR(255),
    tags          TEXT[],
    CONSTRAINT feature_flags_pkey PRIMARY KEY (id)
);

CREATE TABLE flag_environment_settings
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    feature_flag_id       BIGINT                                    NOT NULL,
    environment_id        BIGINT                                    NOT NULL,
    is_enabled            BOOLEAN                     DEFAULT FALSE NOT NULL,
    default_variation_id  BIGINT,
    fallback_variation_id BIGINT,
    created_at            TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT flag_environment_settings_pkey PRIMARY KEY (id)
);

CREATE TABLE flag_evaluations
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    feature_flag_id   BIGINT                                    NOT NULL,
    environment_id    BIGINT                                    NOT NULL,
    user_key          VARCHAR(255)                              NOT NULL,
    user_attributes   JSONB,
    variation_value   TEXT,
    targeting_rule_id BIGINT,
    evaluation_reason VARCHAR(100),
    created_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT flag_evaluations_pkey PRIMARY KEY (id)
);

CREATE TABLE flag_variations
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    feature_flag_id BIGINT                                    NOT NULL,
    name            VARCHAR(255)                              NOT NULL,
    value           TEXT                                      NOT NULL,
    description     TEXT,
    sort_order      INTEGER                     DEFAULT 0     NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT flag_variations_pkey PRIMARY KEY (id)
);

CREATE TABLE organizations
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    name        VARCHAR(255)                              NOT NULL,
    slug        VARCHAR(100)                              NOT NULL,
    description TEXT,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    is_active   BOOLEAN                     DEFAULT TRUE  NOT NULL,
    CONSTRAINT organizations_pkey PRIMARY KEY (id)
);

CREATE TABLE projects
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    organization_id BIGINT                                    NOT NULL,
    name            VARCHAR(255)                              NOT NULL,
    key             VARCHAR(100)                              NOT NULL,
    description     TEXT,
    created_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    is_active       BOOLEAN                     DEFAULT TRUE  NOT NULL,
    CONSTRAINT projects_pkey PRIMARY KEY (id)
);

CREATE TABLE segment_targeting_rules
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    targeting_rule_id BIGINT                                    NOT NULL,
    user_segment_id   BIGINT                                    NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT segment_targeting_rules_pkey PRIMARY KEY (id)
);

CREATE TABLE targeting_rules
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    flag_environment_setting_id BIGINT                                    NOT NULL,
    name                        VARCHAR(255),
    conditions                  JSONB                                     NOT NULL,
    variation_id                BIGINT,
    percentage_rollout          JSONB,
    sort_order                  INTEGER                     DEFAULT 0     NOT NULL,
    is_enabled                  BOOLEAN                     DEFAULT TRUE  NOT NULL,
    created_at                  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at                  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT targeting_rules_pkey PRIMARY KEY (id)
);

CREATE TABLE user_segments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    project_id  BIGINT                                    NOT NULL,
    name        VARCHAR(255)                              NOT NULL,
    key         VARCHAR(100)                              NOT NULL,
    description TEXT,
    conditions  JSONB                                     NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT user_segments_pkey PRIMARY KEY (id)
);
